name: Publish Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-cache
          path: .cache
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.6.0 mkdocs-material==9.6.12 mkdocs-redirects==1.2.2
      
      - name: Debug and fix directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Docs directory contents:"
          ls -la docs/
          
          # Create the proper overrides directory
          mkdir -p overrides
          cp -r docs/overrides/* overrides/ 2>/dev/null || echo "No files to copy"
          
          # If mkdocs.yml contains both docs_dir and needs the overrides directly in it
          echo "Structure created. Running build..."
          
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force --verbose 