name: Publish Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs-material==9.6.12 mkdocs-redirects==1.2.2
      - name: Create overrides directory if it doesn't exist
        run: |
          mkdir -p overrides
          cp -r docs/overrides/* overrides/ 2>/dev/null || true
      - run: mkdocs gh-deploy --force