name: Publish Docs
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      # Set up Node.js for TypeDoc generation
      # Note: We need Node.js 20+ for some of our dev dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Install dependencies and generate TypeDoc documentation
      # Note: We generate the API reference docs during the build process
      # rather than committing them to the repository
      - name: Install Node.js dependencies and generate API docs
        run: |
          npm install
          npm run docs
      
      # Now set up Python for MkDocs
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs-material mkdocs-redirects
      - name: Debug directory structure
        run: |
          echo "Checking if overrides directory exists:"
          if [ -d "docs/overrides" ]; then
            echo "✅ docs/overrides directory exists"
            ls -la docs/overrides/
          else
            echo "❌ docs/overrides directory does not exist"
            echo "Creating it..."
            mkdir -p docs/overrides
            echo "{% extends 'base.html' %}" > docs/overrides/main.html
          fi
      - name: Deploy documentation
        run: mkdocs gh-deploy --force